# Stage 1: Build stage
FROM maven:3.9.9-eclipse-temurin-22 AS builder

WORKDIR /app

# Chỉ copy pom.xml trước để cache dependency
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Sau đó copy source code
COPY src ./src

# Build ứng dụng
RUN mvn clean package -DskipTests

# Stage 2: Run stage
FROM eclipse-temurin:22-jdk-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
