name: CI/CD Docker Build & Push

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: chin2109/shopease_backend:latest

    - name: Build frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./UI
        push: true
        tags: chin2109/shopease_frontend:latest

    - name: Build database image
      uses: docker/build-push-action@v4
      with:
        context: ./database
        push: true
        tags: chin2109/shopease_db:latest
